# Generated by Django 6.0.7 on 2026-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_photos/",
                verbose_name="Фотография пользователя",
            ),
        ),
    ]
