# Generated by Django 6.0.7 on 2026-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admin", "Администратор")],
                default="user",
                verbose_name="Роль",
            ),
        ),
    ]
