version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: bulettin_board_db
    environment:
      POSTGRES_DB: bulletin_board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data
    restart: unless-stopped

volumes:
  postgres_data: