# Generated by Django 6.0.7 on 2026-07-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
